[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'process_tweet'
version = '0.0.1'
authors = [
    {name = 'Abir Dey', email = 'abirdey43@gmail.com'},
]
description = 'A package to make the nltk processing tweets bit easier'